version: '3'

services:
  # Honeypots
  cowrie:
    image: cowrie/cowrie
    container_name: cowrie
    restart: always
    ports:
      - "2222:2222" # SSH
      - "2223:2223" # Telnet
    volumes:
      - ./cowrie/var:/cowrie/cowrie-git/var
      - ./cowrie/etc:/cowrie/cowrie-git/etc
    networks:
      - honeynet

  conpot:
    image: honeynet/conpot
    container_name: conpot
    restart: always
    ports:
      - "80:80"     # HTTP
      - "102:102"   # S7 Comm
      - "502:502"   # Modbus
      - "161:161/udp" # SNMP
    volumes:
      - ./conpot/logs:/var/log/conpot
    networks:
      - honeynet

  # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - honeynet

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./cowrie/var:/mnt/cowrie/var:ro
      - ./conpot/logs:/mnt/conpot/logs:ro
    depends_on:
      - elasticsearch
    networks:
      - honeynet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - honeynet

volumes:
  es_data:

networks:
  honeynet:
    driver: bridge
